export const LOAD_TREE_DATA = 'LOAD_TREE_DATA'
export const TREE_SHOW_CHECK = 'TREE_SHOW_CHECK'
export const RECIEVE_DATA = 'RECIEVE_DATA'




//CUSTOMER ACTION
export const GO_TO_FIRST = 'GO_TO_FIRST'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const LOAD_ALL_CUSTOMER = 'LOAD_ALL_CUSTOMER'
export const LOAD_ONE_CUSTOMER = 'LOAD_ONE_CUSTOMER'
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'
